name: Recette PROD

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  recette:
    uses: ./.github/workflows/recette-checks.yml
    with:
      url: "https://ayman-mehdi.github.io/web-cv/"
      env_name: PROD
